/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElonJoylashRouteImport } from './routes/elon-joylash'
import { Route as IpotekaRouteImport } from './routes/ipoteka'
import { Route as KirishRouteImport } from './routes/kirish'
import { Route as NarxlarRouteImport } from './routes/narxlar'
import { Route as RoyxatdanOtishRouteImport } from './routes/royxatdan-otish'
import { Route as SevimlilarRouteImport } from './routes/sevimlilar'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardBildirishnomalarRouteImport } from './routes/dashboard/bildirishnomalar'
import { Route as DashboardElonlarimRouteImport } from './routes/dashboard/elonlarim'
import { Route as DashboardKorishlarRouteImport } from './routes/dashboard/korishlar'
import { Route as DashboardSorovlarRouteImport } from './routes/dashboard/sorovlar'
import { Route as DashboardSozlamalarRouteImport } from './routes/dashboard/sozlamalar'
import { Route as ElonlarIndexRouteImport } from './routes/elonlar/index'
import { Route as ElonlarIdRouteImport } from './routes/elonlar/$id'
import { Route as ApiAdminPropertiesRouteImport } from './routes/api/admin/properties'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiFavoritesIndexRouteImport } from './routes/api/favorites/index'
import { Route as ApiFavoritesFoldersRouteImport } from './routes/api/favorites/folders'
import { Route as ApiLeadsIndexRouteImport } from './routes/api/leads/index'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiPaymentsIndexRouteImport } from './routes/api/payments/index'
import { Route as ApiPaymentsClickRouteImport } from './routes/api/payments/click'
import { Route as ApiPaymentsPaymeRouteImport } from './routes/api/payments/payme'
import { Route as ApiPaymentsPricingRouteImport } from './routes/api/payments/pricing'
import { Route as ApiPropertiesIndexRouteImport } from './routes/api/properties/index'
import { Route as ApiPropertiesIdRouteImport } from './routes/api/properties/$id'
import { Route as ApiPropertiesFeaturedRouteImport } from './routes/api/properties/featured'
import { Route as ApiPropertiesStatsRouteImport } from './routes/api/properties/stats'
import { Route as ApiViewingRequestsIndexRouteImport } from './routes/api/viewing-requests/index'
import { Route as ApiViewingRequestsIdRouteImport } from './routes/api/viewing-requests/$id'
import { Route as ApiPropertiesIdContactRouteImport } from './routes/api/properties/$id.contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElonJoylashRoute = ElonJoylashRouteImport.update({
  id: '/elon-joylash',
  path: '/elon-joylash',
  getParentRoute: () => rootRouteImport,
} as any)
const IpotekaRoute = IpotekaRouteImport.update({
  id: '/ipoteka',
  path: '/ipoteka',
  getParentRoute: () => rootRouteImport,
} as any)
const KirishRoute = KirishRouteImport.update({
  id: '/kirish',
  path: '/kirish',
  getParentRoute: () => rootRouteImport,
} as any)
const NarxlarRoute = NarxlarRouteImport.update({
  id: '/narxlar',
  path: '/narxlar',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyxatdanOtishRoute = RoyxatdanOtishRouteImport.update({
  id: '/royxatdan-otish',
  path: '/royxatdan-otish',
  getParentRoute: () => rootRouteImport,
} as any)
const SevimlilarRoute = SevimlilarRouteImport.update({
  id: '/sevimlilar',
  path: '/sevimlilar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBildirishnomalarRoute =
  DashboardBildirishnomalarRouteImport.update({
    id: '/dashboard/bildirishnomalar',
    path: '/dashboard/bildirishnomalar',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardElonlarimRoute = DashboardElonlarimRouteImport.update({
  id: '/dashboard/elonlarim',
  path: '/dashboard/elonlarim',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKorishlarRoute = DashboardKorishlarRouteImport.update({
  id: '/dashboard/korishlar',
  path: '/dashboard/korishlar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSorovlarRoute = DashboardSorovlarRouteImport.update({
  id: '/dashboard/sorovlar',
  path: '/dashboard/sorovlar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSozlamalarRoute = DashboardSozlamalarRouteImport.update({
  id: '/dashboard/sozlamalar',
  path: '/dashboard/sozlamalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ElonlarIndexRoute = ElonlarIndexRouteImport.update({
  id: '/elonlar/',
  path: '/elonlar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElonlarIdRoute = ElonlarIdRouteImport.update({
  id: '/elonlar/$id',
  path: '/elonlar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPropertiesRoute = ApiAdminPropertiesRouteImport.update({
  id: '/api/admin/properties',
  path: '/api/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesIndexRoute = ApiFavoritesIndexRouteImport.update({
  id: '/api/favorites/',
  path: '/api/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesFoldersRoute = ApiFavoritesFoldersRouteImport.update({
  id: '/api/favorites/folders',
  path: '/api/favorites/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsIndexRoute = ApiLeadsIndexRouteImport.update({
  id: '/api/leads/',
  path: '/api/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIndexRoute = ApiPaymentsIndexRouteImport.update({
  id: '/api/payments/',
  path: '/api/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsClickRoute = ApiPaymentsClickRouteImport.update({
  id: '/api/payments/click',
  path: '/api/payments/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsPaymeRoute = ApiPaymentsPaymeRouteImport.update({
  id: '/api/payments/payme',
  path: '/api/payments/payme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsPricingRoute = ApiPaymentsPricingRouteImport.update({
  id: '/api/payments/pricing',
  path: '/api/payments/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesIndexRoute = ApiPropertiesIndexRouteImport.update({
  id: '/api/properties/',
  path: '/api/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesIdRoute = ApiPropertiesIdRouteImport.update({
  id: '/api/properties/$id',
  path: '/api/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesFeaturedRoute = ApiPropertiesFeaturedRouteImport.update({
  id: '/api/properties/featured',
  path: '/api/properties/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesStatsRoute = ApiPropertiesStatsRouteImport.update({
  id: '/api/properties/stats',
  path: '/api/properties/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewingRequestsIndexRoute = ApiViewingRequestsIndexRouteImport.update({
  id: '/api/viewing-requests/',
  path: '/api/viewing-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewingRequestsIdRoute = ApiViewingRequestsIdRouteImport.update({
  id: '/api/viewing-requests/$id',
  path: '/api/viewing-requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesIdContactRoute = ApiPropertiesIdContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ApiPropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elon-joylash': typeof ElonJoylashRoute
  '/ipoteka': typeof IpotekaRoute
  '/kirish': typeof KirishRoute
  '/narxlar': typeof NarxlarRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/bildirishnomalar': typeof DashboardBildirishnomalarRoute
  '/dashboard/elonlarim': typeof DashboardElonlarimRoute
  '/dashboard/korishlar': typeof DashboardKorishlarRoute
  '/dashboard/sorovlar': typeof DashboardSorovlarRoute
  '/dashboard/sozlamalar': typeof DashboardSozlamalarRoute
  '/elonlar/$id': typeof ElonlarIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/elonlar/': typeof ElonlarIndexRoute
  '/api/admin/properties': typeof ApiAdminPropertiesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/favorites/folders': typeof ApiFavoritesFoldersRoute
  '/api/payments/click': typeof ApiPaymentsClickRoute
  '/api/payments/payme': typeof ApiPaymentsPaymeRoute
  '/api/payments/pricing': typeof ApiPaymentsPricingRoute
  '/api/properties/$id': typeof ApiPropertiesIdRouteWithChildren
  '/api/properties/featured': typeof ApiPropertiesFeaturedRoute
  '/api/properties/stats': typeof ApiPropertiesStatsRoute
  '/api/viewing-requests/$id': typeof ApiViewingRequestsIdRoute
  '/api/favorites/': typeof ApiFavoritesIndexRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/properties/': typeof ApiPropertiesIndexRoute
  '/api/viewing-requests/': typeof ApiViewingRequestsIndexRoute
  '/api/properties/$id/contact': typeof ApiPropertiesIdContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elon-joylash': typeof ElonJoylashRoute
  '/ipoteka': typeof IpotekaRoute
  '/kirish': typeof KirishRoute
  '/narxlar': typeof NarxlarRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/bildirishnomalar': typeof DashboardBildirishnomalarRoute
  '/dashboard/elonlarim': typeof DashboardElonlarimRoute
  '/dashboard/korishlar': typeof DashboardKorishlarRoute
  '/dashboard/sorovlar': typeof DashboardSorovlarRoute
  '/dashboard/sozlamalar': typeof DashboardSozlamalarRoute
  '/elonlar/$id': typeof ElonlarIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/elonlar': typeof ElonlarIndexRoute
  '/api/admin/properties': typeof ApiAdminPropertiesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/favorites/folders': typeof ApiFavoritesFoldersRoute
  '/api/payments/click': typeof ApiPaymentsClickRoute
  '/api/payments/payme': typeof ApiPaymentsPaymeRoute
  '/api/payments/pricing': typeof ApiPaymentsPricingRoute
  '/api/properties/$id': typeof ApiPropertiesIdRouteWithChildren
  '/api/properties/featured': typeof ApiPropertiesFeaturedRoute
  '/api/properties/stats': typeof ApiPropertiesStatsRoute
  '/api/viewing-requests/$id': typeof ApiViewingRequestsIdRoute
  '/api/favorites': typeof ApiFavoritesIndexRoute
  '/api/leads': typeof ApiLeadsIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/payments': typeof ApiPaymentsIndexRoute
  '/api/properties': typeof ApiPropertiesIndexRoute
  '/api/viewing-requests': typeof ApiViewingRequestsIndexRoute
  '/api/properties/$id/contact': typeof ApiPropertiesIdContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elon-joylash': typeof ElonJoylashRoute
  '/ipoteka': typeof IpotekaRoute
  '/kirish': typeof KirishRoute
  '/narxlar': typeof NarxlarRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/bildirishnomalar': typeof DashboardBildirishnomalarRoute
  '/dashboard/elonlarim': typeof DashboardElonlarimRoute
  '/dashboard/korishlar': typeof DashboardKorishlarRoute
  '/dashboard/sorovlar': typeof DashboardSorovlarRoute
  '/dashboard/sozlamalar': typeof DashboardSozlamalarRoute
  '/elonlar/$id': typeof ElonlarIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/elonlar/': typeof ElonlarIndexRoute
  '/api/admin/properties': typeof ApiAdminPropertiesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/favorites/folders': typeof ApiFavoritesFoldersRoute
  '/api/payments/click': typeof ApiPaymentsClickRoute
  '/api/payments/payme': typeof ApiPaymentsPaymeRoute
  '/api/payments/pricing': typeof ApiPaymentsPricingRoute
  '/api/properties/$id': typeof ApiPropertiesIdRouteWithChildren
  '/api/properties/featured': typeof ApiPropertiesFeaturedRoute
  '/api/properties/stats': typeof ApiPropertiesStatsRoute
  '/api/viewing-requests/$id': typeof ApiViewingRequestsIdRoute
  '/api/favorites/': typeof ApiFavoritesIndexRoute
  '/api/leads/': typeof ApiLeadsIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/properties/': typeof ApiPropertiesIndexRoute
  '/api/viewing-requests/': typeof ApiViewingRequestsIndexRoute
  '/api/properties/$id/contact': typeof ApiPropertiesIdContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elon-joylash'
    | '/ipoteka'
    | '/kirish'
    | '/narxlar'
    | '/royxatdan-otish'
    | '/sevimlilar'
    | '/api/upload'
    | '/dashboard/bildirishnomalar'
    | '/dashboard/elonlarim'
    | '/dashboard/korishlar'
    | '/dashboard/sorovlar'
    | '/dashboard/sozlamalar'
    | '/elonlar/$id'
    | '/admin/'
    | '/dashboard/'
    | '/elonlar/'
    | '/api/admin/properties'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/favorites/folders'
    | '/api/payments/click'
    | '/api/payments/payme'
    | '/api/payments/pricing'
    | '/api/properties/$id'
    | '/api/properties/featured'
    | '/api/properties/stats'
    | '/api/viewing-requests/$id'
    | '/api/favorites/'
    | '/api/leads/'
    | '/api/notifications/'
    | '/api/payments/'
    | '/api/properties/'
    | '/api/viewing-requests/'
    | '/api/properties/$id/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elon-joylash'
    | '/ipoteka'
    | '/kirish'
    | '/narxlar'
    | '/royxatdan-otish'
    | '/sevimlilar'
    | '/api/upload'
    | '/dashboard/bildirishnomalar'
    | '/dashboard/elonlarim'
    | '/dashboard/korishlar'
    | '/dashboard/sorovlar'
    | '/dashboard/sozlamalar'
    | '/elonlar/$id'
    | '/admin'
    | '/dashboard'
    | '/elonlar'
    | '/api/admin/properties'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/favorites/folders'
    | '/api/payments/click'
    | '/api/payments/payme'
    | '/api/payments/pricing'
    | '/api/properties/$id'
    | '/api/properties/featured'
    | '/api/properties/stats'
    | '/api/viewing-requests/$id'
    | '/api/favorites'
    | '/api/leads'
    | '/api/notifications'
    | '/api/payments'
    | '/api/properties'
    | '/api/viewing-requests'
    | '/api/properties/$id/contact'
  id:
    | '__root__'
    | '/'
    | '/elon-joylash'
    | '/ipoteka'
    | '/kirish'
    | '/narxlar'
    | '/royxatdan-otish'
    | '/sevimlilar'
    | '/api/upload'
    | '/dashboard/bildirishnomalar'
    | '/dashboard/elonlarim'
    | '/dashboard/korishlar'
    | '/dashboard/sorovlar'
    | '/dashboard/sozlamalar'
    | '/elonlar/$id'
    | '/admin/'
    | '/dashboard/'
    | '/elonlar/'
    | '/api/admin/properties'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/favorites/folders'
    | '/api/payments/click'
    | '/api/payments/payme'
    | '/api/payments/pricing'
    | '/api/properties/$id'
    | '/api/properties/featured'
    | '/api/properties/stats'
    | '/api/viewing-requests/$id'
    | '/api/favorites/'
    | '/api/leads/'
    | '/api/notifications/'
    | '/api/payments/'
    | '/api/properties/'
    | '/api/viewing-requests/'
    | '/api/properties/$id/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElonJoylashRoute: typeof ElonJoylashRoute
  IpotekaRoute: typeof IpotekaRoute
  KirishRoute: typeof KirishRoute
  NarxlarRoute: typeof NarxlarRoute
  RoyxatdanOtishRoute: typeof RoyxatdanOtishRoute
  SevimlilarRoute: typeof SevimlilarRoute
  ApiUploadRoute: typeof ApiUploadRoute
  DashboardBildirishnomalarRoute: typeof DashboardBildirishnomalarRoute
  DashboardElonlarimRoute: typeof DashboardElonlarimRoute
  DashboardKorishlarRoute: typeof DashboardKorishlarRoute
  DashboardSorovlarRoute: typeof DashboardSorovlarRoute
  DashboardSozlamalarRoute: typeof DashboardSozlamalarRoute
  ElonlarIdRoute: typeof ElonlarIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ElonlarIndexRoute: typeof ElonlarIndexRoute
  ApiAdminPropertiesRoute: typeof ApiAdminPropertiesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiFavoritesFoldersRoute: typeof ApiFavoritesFoldersRoute
  ApiPaymentsClickRoute: typeof ApiPaymentsClickRoute
  ApiPaymentsPaymeRoute: typeof ApiPaymentsPaymeRoute
  ApiPaymentsPricingRoute: typeof ApiPaymentsPricingRoute
  ApiPropertiesIdRoute: typeof ApiPropertiesIdRouteWithChildren
  ApiPropertiesFeaturedRoute: typeof ApiPropertiesFeaturedRoute
  ApiPropertiesStatsRoute: typeof ApiPropertiesStatsRoute
  ApiViewingRequestsIdRoute: typeof ApiViewingRequestsIdRoute
  ApiFavoritesIndexRoute: typeof ApiFavoritesIndexRoute
  ApiLeadsIndexRoute: typeof ApiLeadsIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiPaymentsIndexRoute: typeof ApiPaymentsIndexRoute
  ApiPropertiesIndexRoute: typeof ApiPropertiesIndexRoute
  ApiViewingRequestsIndexRoute: typeof ApiViewingRequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elon-joylash': {
      id: '/elon-joylash'
      path: '/elon-joylash'
      fullPath: '/elon-joylash'
      preLoaderRoute: typeof ElonJoylashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipoteka': {
      id: '/ipoteka'
      path: '/ipoteka'
      fullPath: '/ipoteka'
      preLoaderRoute: typeof IpotekaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirish': {
      id: '/kirish'
      path: '/kirish'
      fullPath: '/kirish'
      preLoaderRoute: typeof KirishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narxlar': {
      id: '/narxlar'
      path: '/narxlar'
      fullPath: '/narxlar'
      preLoaderRoute: typeof NarxlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royxatdan-otish': {
      id: '/royxatdan-otish'
      path: '/royxatdan-otish'
      fullPath: '/royxatdan-otish'
      preLoaderRoute: typeof RoyxatdanOtishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sevimlilar': {
      id: '/sevimlilar'
      path: '/sevimlilar'
      fullPath: '/sevimlilar'
      preLoaderRoute: typeof SevimlilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bildirishnomalar': {
      id: '/dashboard/bildirishnomalar'
      path: '/dashboard/bildirishnomalar'
      fullPath: '/dashboard/bildirishnomalar'
      preLoaderRoute: typeof DashboardBildirishnomalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/elonlarim': {
      id: '/dashboard/elonlarim'
      path: '/dashboard/elonlarim'
      fullPath: '/dashboard/elonlarim'
      preLoaderRoute: typeof DashboardElonlarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/korishlar': {
      id: '/dashboard/korishlar'
      path: '/dashboard/korishlar'
      fullPath: '/dashboard/korishlar'
      preLoaderRoute: typeof DashboardKorishlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sorovlar': {
      id: '/dashboard/sorovlar'
      path: '/dashboard/sorovlar'
      fullPath: '/dashboard/sorovlar'
      preLoaderRoute: typeof DashboardSorovlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sozlamalar': {
      id: '/dashboard/sozlamalar'
      path: '/dashboard/sozlamalar'
      fullPath: '/dashboard/sozlamalar'
      preLoaderRoute: typeof DashboardSozlamalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elonlar/': {
      id: '/elonlar/'
      path: '/elonlar'
      fullPath: '/elonlar/'
      preLoaderRoute: typeof ElonlarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elonlar/$id': {
      id: '/elonlar/$id'
      path: '/elonlar/$id'
      fullPath: '/elonlar/$id'
      preLoaderRoute: typeof ElonlarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/properties': {
      id: '/api/admin/properties'
      path: '/api/admin/properties'
      fullPath: '/api/admin/properties'
      preLoaderRoute: typeof ApiAdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites/': {
      id: '/api/favorites/'
      path: '/api/favorites'
      fullPath: '/api/favorites/'
      preLoaderRoute: typeof ApiFavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites/folders': {
      id: '/api/favorites/folders'
      path: '/api/favorites/folders'
      fullPath: '/api/favorites/folders'
      preLoaderRoute: typeof ApiFavoritesFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/': {
      id: '/api/leads/'
      path: '/api/leads'
      fullPath: '/api/leads/'
      preLoaderRoute: typeof ApiLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/': {
      id: '/api/payments/'
      path: '/api/payments'
      fullPath: '/api/payments/'
      preLoaderRoute: typeof ApiPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/click': {
      id: '/api/payments/click'
      path: '/api/payments/click'
      fullPath: '/api/payments/click'
      preLoaderRoute: typeof ApiPaymentsClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/payme': {
      id: '/api/payments/payme'
      path: '/api/payments/payme'
      fullPath: '/api/payments/payme'
      preLoaderRoute: typeof ApiPaymentsPaymeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/pricing': {
      id: '/api/payments/pricing'
      path: '/api/payments/pricing'
      fullPath: '/api/payments/pricing'
      preLoaderRoute: typeof ApiPaymentsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/': {
      id: '/api/properties/'
      path: '/api/properties'
      fullPath: '/api/properties/'
      preLoaderRoute: typeof ApiPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/$id': {
      id: '/api/properties/$id'
      path: '/api/properties/$id'
      fullPath: '/api/properties/$id'
      preLoaderRoute: typeof ApiPropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/featured': {
      id: '/api/properties/featured'
      path: '/api/properties/featured'
      fullPath: '/api/properties/featured'
      preLoaderRoute: typeof ApiPropertiesFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/stats': {
      id: '/api/properties/stats'
      path: '/api/properties/stats'
      fullPath: '/api/properties/stats'
      preLoaderRoute: typeof ApiPropertiesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/viewing-requests/': {
      id: '/api/viewing-requests/'
      path: '/api/viewing-requests'
      fullPath: '/api/viewing-requests/'
      preLoaderRoute: typeof ApiViewingRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/viewing-requests/$id': {
      id: '/api/viewing-requests/$id'
      path: '/api/viewing-requests/$id'
      fullPath: '/api/viewing-requests/$id'
      preLoaderRoute: typeof ApiViewingRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/$id/contact': {
      id: '/api/properties/$id/contact'
      path: '/contact'
      fullPath: '/api/properties/$id/contact'
      preLoaderRoute: typeof ApiPropertiesIdContactRouteImport
      parentRoute: typeof ApiPropertiesIdRoute
    }
  }
}

interface ApiPropertiesIdRouteChildren {
  ApiPropertiesIdContactRoute: typeof ApiPropertiesIdContactRoute
}

const ApiPropertiesIdRouteChildren: ApiPropertiesIdRouteChildren = {
  ApiPropertiesIdContactRoute: ApiPropertiesIdContactRoute,
}

const ApiPropertiesIdRouteWithChildren = ApiPropertiesIdRoute._addFileChildren(
  ApiPropertiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElonJoylashRoute: ElonJoylashRoute,
  IpotekaRoute: IpotekaRoute,
  KirishRoute: KirishRoute,
  NarxlarRoute: NarxlarRoute,
  RoyxatdanOtishRoute: RoyxatdanOtishRoute,
  SevimlilarRoute: SevimlilarRoute,
  ApiUploadRoute: ApiUploadRoute,
  DashboardBildirishnomalarRoute: DashboardBildirishnomalarRoute,
  DashboardElonlarimRoute: DashboardElonlarimRoute,
  DashboardKorishlarRoute: DashboardKorishlarRoute,
  DashboardSorovlarRoute: DashboardSorovlarRoute,
  DashboardSozlamalarRoute: DashboardSozlamalarRoute,
  ElonlarIdRoute: ElonlarIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ElonlarIndexRoute: ElonlarIndexRoute,
  ApiAdminPropertiesRoute: ApiAdminPropertiesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiFavoritesFoldersRoute: ApiFavoritesFoldersRoute,
  ApiPaymentsClickRoute: ApiPaymentsClickRoute,
  ApiPaymentsPaymeRoute: ApiPaymentsPaymeRoute,
  ApiPaymentsPricingRoute: ApiPaymentsPricingRoute,
  ApiPropertiesIdRoute: ApiPropertiesIdRouteWithChildren,
  ApiPropertiesFeaturedRoute: ApiPropertiesFeaturedRoute,
  ApiPropertiesStatsRoute: ApiPropertiesStatsRoute,
  ApiViewingRequestsIdRoute: ApiViewingRequestsIdRoute,
  ApiFavoritesIndexRoute: ApiFavoritesIndexRoute,
  ApiLeadsIndexRoute: ApiLeadsIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiPaymentsIndexRoute: ApiPaymentsIndexRoute,
  ApiPropertiesIndexRoute: ApiPropertiesIndexRoute,
  ApiViewingRequestsIndexRoute: ApiViewingRequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
