/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElonJoylashRouteImport } from './routes/elon-joylash'
import { Route as IpotekaRouteImport } from './routes/ipoteka'
import { Route as KirishRouteImport } from './routes/kirish'
import { Route as NarxlarRouteImport } from './routes/narxlar'
import { Route as RoyxatdanOtishRouteImport } from './routes/royxatdan-otish'
import { Route as SevimlilarRouteImport } from './routes/sevimlilar'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ElonlarIndexRouteImport } from './routes/elonlar/index'
import { Route as ElonlarIdRouteImport } from './routes/elonlar/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElonJoylashRoute = ElonJoylashRouteImport.update({
  id: '/elon-joylash',
  path: '/elon-joylash',
  getParentRoute: () => rootRouteImport,
} as any)
const IpotekaRoute = IpotekaRouteImport.update({
  id: '/ipoteka',
  path: '/ipoteka',
  getParentRoute: () => rootRouteImport,
} as any)
const KirishRoute = KirishRouteImport.update({
  id: '/kirish',
  path: '/kirish',
  getParentRoute: () => rootRouteImport,
} as any)
const NarxlarRoute = NarxlarRouteImport.update({
  id: '/narxlar',
  path: '/narxlar',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyxatdanOtishRoute = RoyxatdanOtishRouteImport.update({
  id: '/royxatdan-otish',
  path: '/royxatdan-otish',
  getParentRoute: () => rootRouteImport,
} as any)
const SevimlilarRoute = SevimlilarRouteImport.update({
  id: '/sevimlilar',
  path: '/sevimlilar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElonlarIndexRoute = ElonlarIndexRouteImport.update({
  id: '/elonlar/',
  path: '/elonlar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElonlarIdRoute = ElonlarIdRouteImport.update({
  id: '/elonlar/$id',
  path: '/elonlar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elon-joylash': typeof ElonJoylashRoute
  '/ipoteka': typeof IpotekaRoute
  '/kirish': typeof KirishRoute
  '/narxlar': typeof NarxlarRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/elonlar/$id': typeof ElonlarIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/elonlar/': typeof ElonlarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elon-joylash': typeof ElonJoylashRoute
  '/ipoteka': typeof IpotekaRoute
  '/kirish': typeof KirishRoute
  '/narxlar': typeof NarxlarRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/elonlar/$id': typeof ElonlarIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/elonlar': typeof ElonlarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elon-joylash': typeof ElonJoylashRoute
  '/ipoteka': typeof IpotekaRoute
  '/kirish': typeof KirishRoute
  '/narxlar': typeof NarxlarRoute
  '/royxatdan-otish': typeof RoyxatdanOtishRoute
  '/sevimlilar': typeof SevimlilarRoute
  '/elonlar/$id': typeof ElonlarIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/elonlar/': typeof ElonlarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elon-joylash'
    | '/ipoteka'
    | '/kirish'
    | '/narxlar'
    | '/royxatdan-otish'
    | '/sevimlilar'
    | '/elonlar/$id'
    | '/admin/'
    | '/dashboard/'
    | '/elonlar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elon-joylash'
    | '/ipoteka'
    | '/kirish'
    | '/narxlar'
    | '/royxatdan-otish'
    | '/sevimlilar'
    | '/elonlar/$id'
    | '/admin'
    | '/dashboard'
    | '/elonlar'
  id:
    | '__root__'
    | '/'
    | '/elon-joylash'
    | '/ipoteka'
    | '/kirish'
    | '/narxlar'
    | '/royxatdan-otish'
    | '/sevimlilar'
    | '/elonlar/$id'
    | '/admin/'
    | '/dashboard/'
    | '/elonlar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElonJoylashRoute: typeof ElonJoylashRoute
  IpotekaRoute: typeof IpotekaRoute
  KirishRoute: typeof KirishRoute
  NarxlarRoute: typeof NarxlarRoute
  RoyxatdanOtishRoute: typeof RoyxatdanOtishRoute
  SevimlilarRoute: typeof SevimlilarRoute
  ElonlarIdRoute: typeof ElonlarIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ElonlarIndexRoute: typeof ElonlarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elon-joylash': {
      id: '/elon-joylash'
      path: '/elon-joylash'
      fullPath: '/elon-joylash'
      preLoaderRoute: typeof ElonJoylashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipoteka': {
      id: '/ipoteka'
      path: '/ipoteka'
      fullPath: '/ipoteka'
      preLoaderRoute: typeof IpotekaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirish': {
      id: '/kirish'
      path: '/kirish'
      fullPath: '/kirish'
      preLoaderRoute: typeof KirishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narxlar': {
      id: '/narxlar'
      path: '/narxlar'
      fullPath: '/narxlar'
      preLoaderRoute: typeof NarxlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royxatdan-otish': {
      id: '/royxatdan-otish'
      path: '/royxatdan-otish'
      fullPath: '/royxatdan-otish'
      preLoaderRoute: typeof RoyxatdanOtishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sevimlilar': {
      id: '/sevimlilar'
      path: '/sevimlilar'
      fullPath: '/sevimlilar'
      preLoaderRoute: typeof SevimlilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elonlar/': {
      id: '/elonlar/'
      path: '/elonlar'
      fullPath: '/elonlar/'
      preLoaderRoute: typeof ElonlarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elonlar/$id': {
      id: '/elonlar/$id'
      path: '/elonlar/$id'
      fullPath: '/elonlar/$id'
      preLoaderRoute: typeof ElonlarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElonJoylashRoute: ElonJoylashRoute,
  IpotekaRoute: IpotekaRoute,
  KirishRoute: KirishRoute,
  NarxlarRoute: NarxlarRoute,
  RoyxatdanOtishRoute: RoyxatdanOtishRoute,
  SevimlilarRoute: SevimlilarRoute,
  ElonlarIdRoute: ElonlarIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ElonlarIndexRoute: ElonlarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
